insert into public.traduzioni_ui(namespace,chiave,it,de,fr,en,rm) values
('settings','club.risorse.nome_obbligatorio','Il nome è obbligatorio.','Der Name ist obligatorisch.','Le nom est obligatoire.','The name is required.','Il num è obligatoric.'),
('settings','club.risorse.errore_salvataggio','La risorsa non è stata salvata. Quello che hai scritto è ancora qui: correggi o riprova.','Die Ressource wurde nicht gespeichert. Ihre Eingaben sind noch da: korrigieren oder erneut versuchen.','La ressource n''a pas été enregistrée. Vos saisies sont toujours là : corrigez ou réessayez.','The resource wasn''t saved. What you typed is still here: correct it or try again.','La resursa n''è betg vegnida memorisada. Quai che Vus avais scrit è anc qua: curregi u empruvai anc ina giada.'),
('settings','club.risorse.errore_lettura','Non riesco a leggere le risorse del club. Non significa che non ce ne siano.','Die Ressourcen des Clubs können nicht gelesen werden. Das heisst nicht, dass es keine gibt.','Impossible de lire les ressources du club. Cela ne veut pas dire qu''il n''y en a pas.','The club''s resources can''t be read. That doesn''t mean there are none.','Las resursas dal club na pon betg vegnir legidas. Quai na munta betg ch''i na dettia naginas.'),
('settings','club.risorse.riprova','Riprova','Erneut versuchen','Réessayer','Try again','Empruvar anc ina giada'),
('settings','users.scheda_istruttore.avviso','Hai creato l''accesso per {{nome}}. Per farlo comparire fra gli istruttori del club serve anche la sua scheda.','Sie haben den Zugang für {{nome}} erstellt. Damit die Person bei den Trainern des Clubs erscheint, braucht es auch ihr Profil.','Vous avez créé l''accès pour {{nome}}. Pour que la personne apparaisse parmi les moniteurs du club, il faut aussi sa fiche.','You created the login for {{nome}}. For them to appear among the club''s instructors, they also need an instructor profile.','Vus avais creà l''access per {{nome}}. Per che la persuna cumparia tranter ils instructurs dal club dovri era sia fitgha.'),
('settings','users.scheda_istruttore.crea','Crea la scheda istruttore','Trainerprofil erstellen','Créer la fiche moniteur','Create the instructor profile','Crear la fitgha d''instructur'),
('settings','users.scheda_istruttore.chiudi','Chiudi','Schliessen','Fermer','Close','Serrar'),
('onboarding','avvio.aiuto.istruttore_scheda','Serve la scheda dell''istruttore in «Istruttori»: l''accesso creato in «Utenti» non basta.','Es braucht das Trainerprofil unter «Trainer»: Der Zugang unter «Benutzer» genügt nicht.','Il faut la fiche du moniteur dans « Moniteurs » : l''accès créé dans « Utilisateurs » ne suffit pas.','The instructor needs a profile under «Instructors»: a login created under «Users» isn''t enough.','I dovra la fitgha da l''instructur sut «Instructurs»: l''access creà sut «Utilisaders» na basta betg.'),
('onboarding','avvio.rotte.istruttori','Istruttori','Trainer','Moniteurs','Instructors','Instructurs')
on conflict (namespace,chiave) do update set it=excluded.it,de=excluded.de,fr=excluded.fr,en=excluded.en,rm=excluded.rm;