ALTER TABLE public.corsi ALTER COLUMN giorno DROP NOT NULL;
ALTER TABLE public.corsi ALTER COLUMN giorno DROP DEFAULT;
ALTER TABLE public.corsi ALTER COLUMN ora_inizio DROP NOT NULL;
ALTER TABLE public.corsi ALTER COLUMN ora_inizio DROP DEFAULT;
ALTER TABLE public.corsi ALTER COLUMN ora_fine DROP NOT NULL;
ALTER TABLE public.corsi ALTER COLUMN ora_fine DROP DEFAULT;