INSERT INTO public.traduzioni_ui (namespace,chiave,it,de,fr,en,rm) VALUES
('settings','catalogo.errore_catalogo','Non riesco a leggere il catalogo o l''elenco ufficiale dei livelli, quindi la pagina resta ferma.','Der Katalog oder die offizielle Liste der Stufen kann nicht gelesen werden, daher bleibt die Seite gesperrt.','Impossible de lire le catalogue ou la liste officielle des niveaux, la page reste donc bloquée.','Unable to read the catalogue or the official list of levels, so the page stays locked.','Jau na poss betg leger il catalog u la glista uffiziala dals nivels, perquai resta la pagina bloccada.'),
('settings','catalogo.errore_iscritti','Non riesco a contare gli atleti per livello: gruppi e ore non vengono calcolati.','Die Athletinnen und Athleten pro Stufe können nicht gezählt werden: Gruppen und Stunden werden nicht berechnet.','Impossible de compter les athlètes par niveau : groupes et heures ne sont pas calculés.','Unable to count athletes per level: groups and hours are not calculated.','Jau na poss betg dumbrar las atletas per nivel: gruppas ed uras na vegnan betg calculadas.'),
('settings','catalogo.errore_ore','Non riesco a leggere le disponibilità del ghiaccio.','Die Eisverfügbarkeiten können nicht gelesen werden.','Impossible de lire les disponibilités de glace.','Unable to read the ice availability.','Jau na poss betg leger las disponibilitads dal glatsch.'),
('settings','catalogo.riprova','Riprova','Erneut versuchen','Réessayer','Try again','Empruvar anc ina giada'),
('settings','catalogo.vuoto_livelli_paese','Per il paese del club ({{paese}}) non ci sono livelli configurati nell''elenco ufficiale. Vanno aggiunti prima di poter compilare il catalogo.','Für das Land des Clubs ({{paese}}) sind in der offiziellen Liste keine Stufen eingerichtet. Sie müssen ergänzt werden, bevor der Katalog ausgefüllt werden kann.','Aucun niveau n''est configuré dans la liste officielle pour le pays du club ({{paese}}). Il faut les ajouter avant de pouvoir remplir le catalogue.','No levels are configured in the official list for the club''s country ({{paese}}). They must be added before the catalogue can be filled in.','Per il pajais dal club ({{paese}}) n''èn nagins nivels configurads en la glista uffiziala. Els ston vegnir agiuntads avant ch''il catalog po vegnir emplenì.'),
('settings','catalogo.scegli_livello','Livello da aggiungere','Hinzuzufügende Stufe','Niveau à ajouter','Level to add','Nivel d''agiuntar'),
('settings','catalogo.livello_non_ufficiale','Questo livello non compare nell''elenco ufficiale del paese del club.','Diese Stufe ist nicht in der offiziellen Liste des Clublandes enthalten.','Ce niveau ne figure pas dans la liste officielle du pays du club.','This level is not in the official list for the club''s country.','Quest nivel na cumpara betg en la glista uffiziala dal pajais dal club.'),
('settings','catalogo.iscritti_calcolati','Atleti del club con questo livello, contati dall''anagrafica.','Athletinnen und Athleten des Clubs mit dieser Stufe, aus den Stammdaten gezählt.','Athlètes du club avec ce niveau, comptés à partir des fiches.','Club athletes at this level, counted from the athlete records.','Atletas dal club cun quest nivel, dumbradas da las datas persunalas.'),
('settings','catalogo.vuoto_ore','Disponibilità del ghiaccio non dichiarata.','Eisverfügbarkeit nicht erfasst.','Disponibilité de glace non déclarée.','Ice availability not declared.','Disponibilitad dal glatsch betg declerada.'),
('settings','catalogo.ore_da_risorse','Da: {{risorse}}','Aus: {{risorse}}','Source : {{risorse}}','From: {{risorse}}','Da: {{risorse}}'),
('settings','catalogo.surplus_senza_ore','Non calcolabile senza disponibilità dichiarata.','Ohne erfasste Verfügbarkeit nicht berechenbar.','Non calculable sans disponibilité déclarée.','Cannot be calculated without declared availability.','Betg calculabel senza disponibilitad declerada.'),
('settings','catalogo.surplus_senza_iscritti','Non calcolabile senza il conteggio degli iscritti.','Ohne Zählung der Angemeldeten nicht berechenbar.','Non calculable sans le décompte des inscrits.','Cannot be calculated without the enrolment count.','Betg calculabel senza il dumber dals inscrits.')
ON CONFLICT (namespace,chiave) DO UPDATE SET it=EXCLUDED.it,de=EXCLUDED.de,fr=EXCLUDED.fr,en=EXCLUDED.en,rm=EXCLUDED.rm;